# OUTFIT FINDER
The first step into creating the models is to import the necessary libraries.
and to load the data.

In [132]:
import pandas as pd

# Load the data
styles = 'data/styles.csv'

df = pd.read_csv(styles, error_bad_lines=False, warn_bad_lines=False)
df.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt

## Data Cleaning / PreProcessing
I need to remove all uneccesary columns and rows that are not related to the project.

In [133]:
df = df.drop(columns=['id', 'year', 'productDisplayName'])

In [134]:
df = df[df['masterCategory'] == 'Apparel']
df.head()

  gender masterCategory subCategory  articleType baseColour  season   usage
0    Men        Apparel     Topwear       Shirts  Navy Blue    Fall  Casual
1    Men        Apparel  Bottomwear        Jeans       Blue  Summer  Casual
3    Men        Apparel  Bottomwear  Track Pants      Black    Fall  Casual
4    Men        Apparel     Topwear      Tshirts       Grey  Summer  Casual
5    Men        Apparel     Topwear      Tshirts       Grey  Summer  Casual

In [135]:
df = df.drop(columns=['masterCategory'])
df.head()

  gender subCategory  articleType baseColour  season   usage
0    Men     Topwear       Shirts  Navy Blue    Fall  Casual
1    Men  Bottomwear        Jeans       Blue  Summer  Casual
3    Men  Bottomwear  Track Pants      Black    Fall  Casual
4    Men     Topwear      Tshirts       Grey  Summer  Casual
5    Men     Topwear      Tshirts       Grey  Summer  Casual

## Data Cleaning / PreProcessing 2

Now that the columns are taken care of, I need to take care of the rows.
By checking all the unique values of the columns, I can see what needs to be removed, or changed.

In [136]:
df['gender'].unique()

array(['Men', 'Women', 'Girls', 'Boys', 'Unisex'], dtype=object)

In [137]:
# replace Girls for Women and Boys for Men
df['gender'] = df['gender'].replace('Girls', 'Women')
df['gender'] = df['gender'].replace('Boys', 'Men')
df['gender'].unique()
df.head()

  gender subCategory  articleType baseColour  season   usage
0    Men     Topwear       Shirts  Navy Blue    Fall  Casual
1    Men  Bottomwear        Jeans       Blue  Summer  Casual
3    Men  Bottomwear  Track Pants      Black    Fall  Casual
4    Men     Topwear      Tshirts       Grey  Summer  Casual
5    Men     Topwear      Tshirts       Grey  Summer  Casual

In [138]:
df['subCategory'].unique()

array(['Topwear', 'Bottomwear', 'Innerwear', 'Saree', 'Dress',
       'Loungewear and Nightwear', 'Apparel Set', 'Socks'], dtype=object)

I will remove the following subcategories:
- Socks
- Apparel Set
- Saree
- Innerwear
- Loungewear and Nightwear

Before doing so I will check the value counts to see if there are any other subcategories that need to be removed.

In [139]:
df['subCategory'].value_counts()

Topwear                     15402
Bottomwear                   2694
Innerwear                    1808
Dress                         478
Loungewear and Nightwear      470
Saree                         427
Apparel Set                   106
Socks                          12
Name: subCategory, dtype: int64

In [140]:
delete_subcategories = [
    'Socks', 'Apparel Set', 'Saree', 'Innerwear',
    'Loungewear and Nightwear',
]
df = df[~df['subCategory'].isin(delete_subcategories)]
df['subCategory'].value_counts()

Topwear       15402
Bottomwear     2694
Dress           478
Name: subCategory, dtype: int64

In [141]:
df.head()

  gender subCategory  articleType baseColour  season   usage
0    Men     Topwear       Shirts  Navy Blue    Fall  Casual
1    Men  Bottomwear        Jeans       Blue  Summer  Casual
3    Men  Bottomwear  Track Pants      Black    Fall  Casual
4    Men     Topwear      Tshirts       Grey  Summer  Casual
5    Men     Topwear      Tshirts       Grey  Summer  Casual

## Data Cleaning / PreProcessing 3

Now that the subcategories are taken care of, I will check the unique values of the articleType column.
and remove the following article types:
- Track Pants
- Kurtas
- Waistcoat
- Rain Jacket
- Blazers
- Shrug
- Trousers
- Dupatta
- Capris
- tunics
- Tracksuits
- Kurtis
- Jumpsuit
- Suspenders
- Salwar and Dupatta
- Patiala
- Stockings
- Churidar
- Nehru Jackets
- Salwar
- Lehenga Choli
- Belts
- Rain Trousers
- Suits

In [142]:
df['articleType'].unique()

array(['Shirts', 'Jeans', 'Track Pants', 'Tshirts', 'Tops', 'Sweatshirts',
       'Kurtas', 'Waistcoat', 'Shorts', 'Rain Jacket', 'Dresses',
       'Skirts', 'Blazers', 'Shrug', 'Trousers', 'Dupatta', 'Capris',
       'Tunics', 'Jackets', 'Sweaters', 'Tracksuits', 'Swimwear',
       'Leggings', 'Kurtis', 'Jumpsuit', 'Suspenders',
       'Salwar and Dupatta', 'Patiala', 'Stockings', 'Tights', 'Churidar',
       'Nehru Jackets', 'Salwar', 'Jeggings', 'Rompers', 'Lehenga Choli',
       'Belts', 'Rain Trousers', 'Suits'], dtype=object)

In [143]:
delete_article_types = [
    'Track Pants', 'Kurtas', 'Waistcoat', 'Rain Jacket', 
    'Blazers', 'Shrug', 'Trousers', 'Dupatta', 'Capris',
    'tunics', 'Tracksuits', 'Kurtis', 'Jumpsuit', 'Suspenders',
    'Salwar and Dupatta', 'Patiala', 'Stockings', 'Churidar',
    'Nehru Jackets', 'Salwar', 'Lehenga Choli', 'Belts',
    'Rain Trousers', 'Suits'
]
df = df[~df['articleType'].isin(delete_article_types)]
df['articleType'].unique()

array(['Shirts', 'Jeans', 'Tshirts', 'Tops', 'Sweatshirts', 'Shorts',
       'Dresses', 'Skirts', 'Tunics', 'Jackets', 'Sweaters', 'Swimwear',
       'Leggings', 'Tights', 'Jeggings', 'Rompers'], dtype=object)

In [144]:
df.head()

  gender subCategory articleType baseColour  season   usage
0    Men     Topwear      Shirts  Navy Blue    Fall  Casual
1    Men  Bottomwear       Jeans       Blue  Summer  Casual
4    Men     Topwear     Tshirts       Grey  Summer  Casual
5    Men     Topwear     Tshirts       Grey  Summer  Casual
6    Men     Topwear      Shirts      Green  Summer  Ethnic

## Data Cleaning / PreProcessing 4

Now that the article types are taken care of, I will check the unique values of the baseColour column.

In [145]:
df['baseColour'].unique()

array(['Navy Blue', 'Blue', 'Grey', 'Green', 'Purple', 'White', 'Brown',
       'Pink', 'Black', 'Red', 'Off White', 'Yellow', 'Beige', 'Cream',
       'Olive', 'Magenta', 'Burgundy', 'Maroon', 'Grey Melange', 'Orange',
       'Teal', 'Rust', 'Charcoal', 'Multi', 'Peach', 'Lavender',
       'Mustard', 'Khaki', 'Turquoise Blue', 'Sea Green', 'Coffee Brown',
       'Mushroom Brown', nan, 'Tan', 'Mauve', 'Gold', 'Nude',
       'Lime Green', 'Fluorescent Green'], dtype=object)

In [146]:
df['baseColour'] = df['baseColour'].fillna('Multi')
df['baseColour'].unique()

array(['Navy Blue', 'Blue', 'Grey', 'Green', 'Purple', 'White', 'Brown',
       'Pink', 'Black', 'Red', 'Off White', 'Yellow', 'Beige', 'Cream',
       'Olive', 'Magenta', 'Burgundy', 'Maroon', 'Grey Melange', 'Orange',
       'Teal', 'Rust', 'Charcoal', 'Multi', 'Peach', 'Lavender',
       'Mustard', 'Khaki', 'Turquoise Blue', 'Sea Green', 'Coffee Brown',
       'Mushroom Brown', 'Tan', 'Mauve', 'Gold', 'Nude', 'Lime Green',
       'Fluorescent Green'], dtype=object)

In [147]:
df['season'].unique()

array(['Fall', 'Summer', 'Spring', 'Winter', nan], dtype=object)

Because there are null values in the season column, I will replace them with 'All'.

In [148]:
# replace null values for any
df['season'] = df['season'].fillna('All')
df['season'].unique()

array(['Fall', 'Summer', 'Spring', 'Winter', 'All'], dtype=object)

In [149]:
df.head()

  gender subCategory articleType baseColour  season   usage
0    Men     Topwear      Shirts  Navy Blue    Fall  Casual
1    Men  Bottomwear       Jeans       Blue  Summer  Casual
4    Men     Topwear     Tshirts       Grey  Summer  Casual
5    Men     Topwear     Tshirts       Grey  Summer  Casual
6    Men     Topwear      Shirts      Green  Summer  Ethnic

In [150]:
df['usage'].unique()

array(['Casual', 'Ethnic', 'Formal', 'Sports', 'Smart Casual', nan,
       'Party', 'Travel'], dtype=object)

I will only be removing 'Ethnic' from the 'usage' column.
But replacing any Null values with 'Any'.

In [151]:
delete_usages = [
    'Ethnic'
]
df = df[~df['usage'].isin(delete_usages)]
df['usage'].unique()

array(['Casual', 'Formal', 'Sports', 'Smart Casual', nan, 'Party',
       'Travel'], dtype=object)

In [152]:
df['usage'] = df['usage'].fillna('Any')
df['usage'].unique()

array(['Casual', 'Formal', 'Sports', 'Smart Casual', 'Any', 'Party',
       'Travel'], dtype=object)

Renaming the columns to make them more readable.

In [153]:
df = df.rename(columns={
    'subCategory': 'category',
    'articleType': 'style',
    'baseColour': 'color'
})
df.head()

  gender    category    style      color  season   usage
0    Men     Topwear   Shirts  Navy Blue    Fall  Casual
1    Men  Bottomwear    Jeans       Blue  Summer  Casual
4    Men     Topwear  Tshirts       Grey  Summer  Casual
5    Men     Topwear  Tshirts       Grey  Summer  Casual
7  Women     Topwear   Shirts     Purple  Summer  Casual

In [154]:
# all values will be lower case

for column in df.columns:
    df[column] = df[column].str.lower()
    
df.head()

  gender    category    style      color  season   usage
0    men     topwear   shirts  navy blue    fall  casual
1    men  bottomwear    jeans       blue  summer  casual
4    men     topwear  tshirts       grey  summer  casual
5    men     topwear  tshirts       grey  summer  casual
7  women     topwear   shirts     purple  summer  casual

In [155]:
# save clean data
df.to_csv('data/clean_data.csv', index=False)

In [156]:
# Load the data
df = pd.read_csv('data/clean_data.csv')
df.head()

  gender    category    style      color  season   usage
0    men     topwear   shirts  navy blue    fall  casual
1    men  bottomwear    jeans       blue  summer  casual
2    men     topwear  tshirts       grey  summer  casual
3    men     topwear  tshirts       grey  summer  casual
4  women     topwear   shirts     purple  summer  casual

## Data Preprocessing

Now that the data is clean, I will preprocess the data:
- Encode the categorical columns
- Scale the data
- Split the data into training and testing sets
- Train the models
- Evaluate the models
- Save the models

In [157]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

df.head()

   gender  category  style  color  season  usage
0       0         2      6     22       1      1
1       0         0      2      2       3      1
2       0         2     14     11       3      1
3       0         2     14     11       3      1
4       2         2      6     29       3      1

In [158]:
feature_columns = ['gender','category', 'style', 'color', 'season']
target_column = 'usage'
df.head()

   gender  category  style  color  season  usage
0       0         2      6     22       1      1
1       0         0      2      2       3      1
2       0         2     14     11       3      1
3       0         2     14     11       3      1
4       2         2      6     29       3      1

In [159]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split


# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_columns])
y = df[target_column]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train the KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Evaluate the model
accuracy_percentage = knn.score(X_test, y_test) * 100

accuracy_percentage

82.48663101604278

# Testing

Here im going to test the model with some fake user input, as a proof of theory.

In [165]:
user_input = pd.DataFrame({
    'gender':   ['men', 'men', 'men', 'men', 'men'],
    'category': ['topwear', 'bottomwear','topwear','bottomwear', 'bottomwear'],
    'style':    ['tshirts', 'jeans', 'tshirts', 'jeans', 'shorts'],
    'color':    ['black','blue','red', 'black', 'black'],
    'season':   ['summer','summer','summer', 'summer', 'summer'],
})

for column in user_input.columns:
    user_input[column] = label_encoders[column].transform(user_input[column])
    
user_input_scaled = scaler.transform(user_input)

user_input_scaled

array([[-0.69017081,  0.37324419,  0.79479406, -1.11991484,  0.7900157 ],
       [-0.69017081, -2.90101586, -1.87951168, -1.04702069,  0.7900157 ],
       [-0.69017081,  0.37324419,  0.79479406,  0.99401562,  0.7900157 ],
       [-0.69017081, -2.90101586, -1.87951168, -1.11991484,  0.7900157 ],
       [-0.69017081, -2.90101586, -0.76521762, -1.11991484,  0.7900157 ]])

In [166]:
# get probability of each class, and convert columns to real names

predictions = knn.predict_proba(user_input_scaled)

predictions = pd.DataFrame(predictions, columns=label_encoders['usage'].classes_)

predictions

   any    casual  formal  party  smart casual    sports  travel
0  0.0  0.666667     0.0    0.0           0.0  0.333333     0.0
1  0.0  1.000000     0.0    0.0           0.0  0.000000     0.0
2  0.0  1.000000     0.0    0.0           0.0  0.000000     0.0
3  0.0  1.000000     0.0    0.0           0.0  0.000000     0.0
4  0.0  0.333333     0.0    0.0           0.0  0.666667     0.0

# Save the models and encoders

In [167]:
import joblib

joblib.dump(knn, 'models/knn.joblib')
joblib.dump(scaler, 'models/scaler.joblib')
joblib.dump(label_encoders, 'models/label_encoders.joblib')

['models/label_encoders.joblib']

# Get values for database

In [168]:
# get clean_data.csv
df = pd.read_csv('data/clean_data.csv')
df.head()

  gender    category    style      color  season   usage
0    men     topwear   shirts  navy blue    fall  casual
1    men  bottomwear    jeans       blue  summer  casual
2    men     topwear  tshirts       grey  summer  casual
3    men     topwear  tshirts       grey  summer  casual
4  women     topwear   shirts     purple  summer  casual

In [169]:
# get unique values for each column
unique_values = {}
for column in df.columns:
    unique_values[column] = df[column].unique()
    
for key, value in unique_values.items():
    print(key,':', value)

gender : ['men' 'women' 'unisex']
category : ['topwear' 'bottomwear' 'dress']
style : ['shirts' 'jeans' 'tshirts' 'tops' 'sweatshirts' 'shorts' 'dresses'
 'skirts' 'tunics' 'jackets' 'sweaters' 'swimwear' 'leggings' 'tights'
 'jeggings' 'rompers']
color : ['navy blue' 'blue' 'grey' 'purple' 'white' 'green' 'brown' 'pink' 'black'
 'red' 'off white' 'yellow' 'beige' 'cream' 'olive' 'magenta' 'burgundy'
 'maroon' 'grey melange' 'orange' 'teal' 'rust' 'charcoal' 'multi' 'peach'
 'lavender' 'mustard' 'khaki' 'turquoise blue' 'sea green' 'coffee brown'
 'mushroom brown' 'mauve' 'tan' 'gold' 'nude' 'lime green'
 'fluorescent green']
season : ['fall' 'summer' 'spring' 'winter' 'all']
usage : ['casual' 'formal' 'sports' 'smart casual' 'any' 'party' 'travel']